### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by codesbyshrey** [DevDiscover-Toolkit/app#3]
Create a repository README with directions for:
 - installing the application on a local client
 - managing adjustments for a local database
 - information related to the application development and provided value
 - link to Trello / Jira, Figma wireframing (ideally screenshots), and SDLC outline
 - discussions for future growth or technology changes to scale up
 - scope beyond October project

**Comment by GrantLicata** [comment]
I'll take this on. Should have a PR submitted shortly.
